// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TooTheMoon.Data;

#nullable disable

namespace TooTheMoon.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904063829_AddSeatingPlanner")]
    partial class AddSeatingPlanner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TooTheMoon.Models.RsvpGuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdultsCount")
                        .HasColumnType("integer");

                    b.Property<int>("ChildrenCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DietaryNotes")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FoodIntolerances")
                        .HasColumnType("text");

                    b.Property<bool>("IsAttending")
                        .HasColumnType("boolean");

                    b.Property<int>("MeatCount")
                        .HasColumnType("integer");

                    b.Property<string>("MessageToCouple")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("integer");

                    b.Property<string>("SongRequest")
                        .HasColumnType("text");

                    b.Property<int>("VeganCount")
                        .HasColumnType("integer");

                    b.Property<int>("VeggieCount")
                        .HasColumnType("integer");

                    b.Property<int?>("WeddingTableId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeddingTableId");

                    b.ToTable("RsvpGuests", (string)null);
                });

            modelBuilder.Entity("TooTheMoon.Models.WeddingTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WeddingTables");
                });

            modelBuilder.Entity("TooTheMoon.Models.RsvpGuest", b =>
                {
                    b.HasOne("TooTheMoon.Models.WeddingTable", "WeddingTable")
                        .WithMany("Guests")
                        .HasForeignKey("WeddingTableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WeddingTable");
                });

            modelBuilder.Entity("TooTheMoon.Models.WeddingTable", b =>
                {
                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
